language: python
python:
 - "2.6"
 - "2.7"
env:
 - BEFORE_DJANGO_VERSION=1.5
 - BEFORE_DJANGO_VERSION=1.6
services: mongodb
install:
  - pip install "Django<$BEFORE_DJANGO_VERSION"
  - python setup.py install
script: "python setup.py test"
